using System.Data;
using System.Globalization;
using System.Linq;
using Majorsilence.Crystal.RptEngine;
using Majorsilence.Crystal.Runtime;
using SkiaSharp;

namespace Majorsilence.Crystal.VisualRegression.Tests;

/// <summary>
/// Compares majorsilence.crystal's own PDF render against a checked-in ground-truth
/// screenshot from the real, licensed Crystal Reports engine (tests/reference-renders/,
/// generated by tools/Majorsilence.Crystal.ReferenceRenderer on a dev machine that has
/// that engine installed — see this repo's plan notes).
///
/// Exact pixel equality is not the goal and never will be: the real engine renders via
/// GDI+, ours via SkiaSharp through a different RDL layout engine, so font hinting and
/// subpixel placement differ even when everything is semantically right. What is asserted
/// is <see cref="InkAgreementPercent"/> against a recorded per-case baseline — see that
/// method for why the mean-pixel score it sits beside is *not* assertable.
///
/// These cases can only be as good as the data behind them. The reference images were
/// rendered from the rows saved inside each .rpt, which this pipeline cannot read, so a
/// case with no fixture in tests/reference-data/ renders with no rows and scores ~0 no
/// matter how correct the layout is. Fixtures come from those same saved rows, in two
/// dev-machine-only steps:
///
///   ReferenceRenderer --xls  &lt;report&gt;.rpt  &lt;report&gt;.xls
///   FixtureBuilder           &lt;report&gt;.rpt  &lt;report&gt;.xls  tests/reference-data/&lt;report&gt;.csv
///
/// Only reports whose detail rows survive that export have one; a report that shows only
/// group summaries or a cross-tab does not, and cannot until the saved-data stream itself
/// can be read. BACKLOG.md has the details.
/// </summary>
[TestFixture]
public class VisualRegressionTests
{
    /// <summary>
    /// Measured ink-agreement baselines, asserted as "no worse than", with an improvement
    /// also failing so the number cannot drift up unnoticed and stop meaning anything.
    ///
    /// The zeros are cases with no data fixture: the DataSet's CommandText is a SQL query
    /// against a data source that does not exist at test time, so nothing data-bound
    /// renders and no amount of layout work can move them. Those three report only
    /// aggregates or a cross-tab, and Crystal's data-only export gives what a report
    /// displays, so their detail rows are not obtainable that way — see BACKLOG.
    ///
    /// CustomerList went 1.5% → 8.9% on getting a fixture, → 15.0% on reading the
    /// report's real page size (it is landscape, and was being rendered portrait),
    /// → 16.2% on stopping the table from synthesizing a header row of column names,
    /// and → 28.9% on giving the table its real geometry: columns as wide as the gap to
    /// the next one, and a page margin of a sixth of an inch rather than a half.
    ///
    /// It then went *down* to 28.4% on reading text alignment correctly, which is worth
    /// spelling out because it looks like a regression and is not. Left-aligned, this
    /// report's title printed on top of the logo, so it cost nothing: those cells were
    /// inked in both images anyway. Centred - which is where Crystal puts it, within 70
    /// pixels - it moves off the logo and inks cells of its own, at a height the
    /// reference does not have a title at, because our whole header block still sits
    /// about four tenths of an inch too low. The metric is charging the alignment fix for
    /// a section-ordering bug that was already there; see BACKLOG.
    ///
    /// → 35.0% on a table band's contents being positioned against the table rather
    /// than the page. Its column labels ran 0.08in past the end of the table holding them.
    ///
    /// → 34.8% on the engine drawing images at the size their report item asks for
    /// rather than a third larger, which is where its logo went.
    ///
    /// → 32.4% once that section-ordering bug was fixed: Crystal prints the Report
    /// Header above the Page Header on page one, and RDL's PageHeader cannot, so the page
    /// header moved into the table's own Header band. The title and logo now sit at the
    /// top of the page with the column labels below them, which is the arrangement the
    /// reference has.
    ///
    /// SalesByCustomer-Grouped went 3.6% to 3.7% on its group-header labels being emitted
    /// once instead of twice, then to 20.6% - its largest jump - on the report header
    /// getting a full-width table of its own instead of riding inside the details table,
    /// which is narrower than the page and indented to its first column. The title and
    /// logo now start at the top left corner, where Crystal has them. Then to 32.4% on the
    /// engine's image sizing: its logo was being drawn a third oversized, over the start of
    /// the title.
    ///
    /// SalesByCustomer-Grouped is the second case with a fixture and the first grouped
    /// one. It renders the right structure — group header, detail row, subtotal, a page
    /// break per group — so its number is low for real remaining reasons rather than for
    /// want of data.
    ///
    /// Top5USAsubCanada has no fixture and still scores above zero, because its report
    /// header and footer are static and now land where Crystal puts them.
    ///
    /// Five cases were added at once when the fixture route was swept across the whole
    /// public corpus. They divide sharply, and the division is the useful part.
    ///
    /// Country-Region-Sort (28.7%) and boyum__SampleReport (37.1%) - the best score in the
    /// suite, and the first case here from a different report author - render about as much
    /// ink as their references do (5.5% against 5.3%, 0.7% against 0.6%). They are ordinary
    /// list reports and what is left between them and 100% is placement, not content.
    ///
    /// boyum__SampleReport then went 37.1% -> 38.4% on a band no longer being clamped to
    /// its table's left edge. Its print date sits at the page margin, an inch and a third
    /// left of the first data column, and came out printed on top of that column's heading.
    ///
    /// Then the numeric format - decimal places and the currency symbol, from the second of
    /// the two tag-249 records each object carries. SalesByCustomer-Grouped 41.7 -> 42.3:
    /// both its amounts read $53.90 instead of 53.9. Only that report has a fixture with a
    /// currency field, so nothing else moves.
    ///
    /// Then object borders: what the report draws as a box around its title, a rule under
    /// a column label, or a frame around a subtotal is border formatting on the object -
    /// tag 237 in the file - not a line object. SalesByCustomer-Grouped 34.0 -> 41.7, its
    /// largest single move, and the first change to touch it since its own header table.
    /// Nothing else moves because no other fixture-backed report uses borders.
    ///
    /// Then the engine's point: it converted inches to points with 72.27 - TeX's printer's
    /// point - where PDF, CSS and GDI all define 1pt = 1/72in. Every dimension written in
    /// inches came out 0.375% oversized: a Letter page had a MediaBox of 794x614 instead of
    /// 612x792, and CustomerList's 0.215in rows rendered 15.535pt tall instead of 15.48,
    /// a pitch error that put its rows half a cell adrift by the bottom of the page. Fixed
    /// in Majorsilence.Reporting (RSize). CustomerList 57.6 -> 60.9 - its rows now sit on
    /// Crystal's - while Country-Region-Sort 64.4 -> 60.9 and SampleReport 58.3 -> 57.1.
    /// Those two dips are quantisation, not movement: at 24px cells both are unchanged
    /// (88.0 and 86.5), and the render is now on a correctly-sized page with exact row
    /// pitch, so the 8px numbers resettle around sub-cell boundaries. All recorded at
    /// measured values.
    ///
    /// Then the font style bits, and this one moved two of them DOWN, which is worth
    /// spelling out. The parser read 0x02 as italic and 0x04 as underline; neither bit is
    /// ever set in either corpus, so both attributes were dead. The bits the files use are
    /// 0x1 and 0x10000, and with those the column headings underline where Crystal
    /// underlines them. CustomerList 57.2 -> 57.6, but Country-Region-Sort 64.6 -> 64.4 and
    /// SampleReport 59.2 -> 58.3. The text does not move at all - the renders differ by 48
    /// bytes of stroke. That dip was first blamed on the stroke being drawn 7px low and the
    /// width of the textbox; measuring the ink bands showed both claims false. Each rule
    /// sits 2-3px under its own glyphs and is a few px wider than them, in both renders.
    /// What differs is the glyphs: for the same string in the same nominal font ours is
    /// about 11% wider, and ours is the one matching Arial's published metrics. See BACKLOG
    /// - it is a difference between the two renderers, not a defect either side of this
    /// suite can fix, and it caps what these numbers can reach.
    ///
    /// Then a detail cell padded back to the width of the field the report drew, rather
    /// than filling a column that is as wide as the gap to the next one: Country-Region-Sort
    /// 61.0 -> 64.6, CustomerList 55.1 -> 57.2, SalesByCustomer-Grouped 33.9 -> 34.7. A
    /// right-aligned number had been ending flush against the next column's first word.
    ///
    /// Then the big one: a detail cell no longer grows. Crystal's Can Grow is a per-object
    /// flag that is off by default, and writing CanGrow=true on every table cell threw away
    /// the row height taken from the object's own bounds. In a table that is not a one-off
    /// error but a row pitch - our rows came out 53.5px apart against Crystal's 46px, a
    /// third of an inch of drift by the thirteenth row. Country-Region-Sort 29.8 -> 59.6,
    /// SampleReport 38.7 -> 59.1, CustomerList 36.7 -> 55.1, the largest movement this
    /// suite has recorded. Reports without a fixture cannot show it, and the grouped report
    /// does not move because its own remaining faults are elsewhere.
    ///
    /// Every fixture-backed case had already moved at once - CustomerList 35.0 -> 36.7,
    /// SalesByCustomer-Grouped 32.4 -> 33.9, Country-Region-Sort 28.7 -> 29.8,
    /// SampleReport 38.4 -> 38.7 - on a page footer of Crystal special fields staying in
    /// RDL's own PageFooter instead of being routed into the details table. The table's
    /// footer band renders where the table ends; a page footer belongs at the foot of the
    /// page, which is where Crystal puts it and where these references now go.
    ///
    /// BeforeTV, Orders10k and Orders5-150 rendered almost blank pages for a long time -
    /// 0.14% ink against references carrying 2.3-8.0%. All three have a record-selection
    /// formula testing a field against a report parameter, which is how Crystal spells a
    /// range - {Orders.Order Amount} = {?Order_Amt_Range}. It converts faithfully to an RDL
    /// DataSet Filter, and then no parameter value exists at render time, so the comparison
    /// was false for every row and the report selected nothing. Making an unanswered
    /// parameter inert rather than exclusive took them to 57.4%, 57.1% and 51.1% - the
    /// largest movement in this suite's history, and the three of them had been the largest
    /// remaining gap in it.
    /// </summary>
    private static readonly Dictionary<string, double> InkAgreementBaseline = new()
    {
        ["benbrahim777__CustomerList/1"] = 60.9,
        ["benbrahim777__SalesByCustomer-Grouped/1"] = 42.3,
        ["benbrahim777__Top5USAsubCanada/1"] = 2.9,
        ["benbrahim777__Canada-CrossTab/1"] = 0.1,
        ["benbrahim777__Top5USA-piechart/1"] = 0.0,
        ["benbrahim777__Top5USAsubCanada/2"] = 0.0,
        ["benbrahim777__Country-Region-Sort/1"] = 60.9,
        ["boyum__SampleReport/1"] = 57.0,
        ["benbrahim777__BeforeTV/1"] = 57.4,
        ["benbrahim777__Orders10k/1"] = 57.1,
        ["benbrahim777__Orders5-150/1"] = 51.1,
    };

    // Slack below the recorded baseline, for anti-aliasing and font-hinting jitter between
    // runs. Small on purpose: the baselines are near zero, so a real drop is still visible.
    private const double BaselineTolerance = 1.0;

    [OneTimeSetUp]
    public void Init() => ReportEngine.Init();

    private static string CorpusPath(string name) =>
        Path.GetFullPath($"../../../../rpt-corpus/{name}", AppContext.BaseDirectory);

    private static string ReferencePath(string corpusStem, int pageIndex) =>
        Path.GetFullPath(
            $"../../../../reference-renders/{corpusStem}/real-crystal-page-{pageIndex + 1}.png",
            AppContext.BaseDirectory);

    [TestCase("benbrahim777__CustomerList.rpt", "benbrahim777__CustomerList", 0)]
    [TestCase("benbrahim777__SalesByCustomer-Grouped.rpt", "benbrahim777__SalesByCustomer-Grouped", 0)]
    [TestCase("benbrahim777__Top5USAsubCanada.rpt", "benbrahim777__Top5USAsubCanada", 0)]
    [TestCase("benbrahim777__Top5USAsubCanada.rpt", "benbrahim777__Top5USAsubCanada", 1)]
    [TestCase("benbrahim777__Canada-CrossTab.rpt", "benbrahim777__Canada-CrossTab", 0)]
    [TestCase("benbrahim777__Top5USA-piechart.rpt", "benbrahim777__Top5USA-piechart", 0)]
    [TestCase("benbrahim777__Country-Region-Sort.rpt", "benbrahim777__Country-Region-Sort", 0)]
    [TestCase("benbrahim777__Orders5-150.rpt", "benbrahim777__Orders5-150", 0)]
    [TestCase("benbrahim777__Orders10k.rpt", "benbrahim777__Orders10k", 0)]
    [TestCase("benbrahim777__BeforeTV.rpt", "benbrahim777__BeforeTV", 0)]
    [TestCase("boyum__SampleReport.rpt", "boyum__SampleReport", 0)]
    public async Task ExportedPdf_MatchesRealCrystalReference(string corpusFile, string referenceStem, int pageIndex)
    {
        string rptPath = CorpusPath(corpusFile);
        Assume.That(File.Exists(rptPath), Is.True, $"{corpusFile} not found — run scripts/download-test-rpts.sh");

        string referencePngPath = ReferencePath(referenceStem, pageIndex);
        Assume.That(File.Exists(referencePngPath), Is.True, $"Reference image not found: {referencePngPath}");

        // The reference was rendered from the rows saved inside the .rpt, which this
        // pipeline cannot read (see BACKLOG). Where a data fixture exists — exported from
        // those same saved rows by ReferenceRenderer --xls and FixtureBuilder — push it, so
        // the two renders are actually comparable. Without one the render has no rows at all
        // and every data-bound item comes out empty.
        var overrides = new RuntimeOverrides();
        string dataFixturePath = Path.GetFullPath(
            $"../../../../reference-data/{referenceStem}.csv", AppContext.BaseDirectory);
        if (File.Exists(dataFixturePath))
            overrides.Data = LoadCsvFixture(dataFixturePath);

        byte[] pdfBytes;
        using (var rpt = File.OpenRead(rptPath))
        {
            pdfBytes = await new ReportEngine().ExportAsync(rpt, overrides, ExportFormat.Pdf);
        }

        using var ourPdfStream = new MemoryStream(pdfBytes);
        // A missing page is itself a finding worth naming, rather than an
        // ArgumentOutOfRangeException from the rasterizer.
        int ourPageCount = PDFtoImage.Conversion.GetPageCount(ourPdfStream, leaveOpen: true);
        ourPdfStream.Position = 0;

        // A page only exists if there are rows to fill it. With no data fixture the report
        // renders whatever is static and stops, so a reference page beyond ours says
        // something about the missing data rather than about layout - skip rather than fail,
        // and the case goes live the moment that report gets a fixture. Where a fixture DOES
        // exist a short render is a real defect and still fails.
        //
        // Top5USAsubCanada's second page is the case this exists for, and it is out of reach
        // twice over: the report has no fixture, and that page is a subreport, which
        // RuntimeOverrides.Data would not reach even with one - ReportEngine pushes only to
        // the main report's own DataSet1. It had been failing this suite continuously.
        // Ignore rather than Assume: an inconclusive result drops the case out of the run
        // entirely, where an ignored one stays visible in the count as a skip.
        if (overrides.Data is null && ourPageCount <= pageIndex)
            Assert.Ignore($"{referenceStem}: no data fixture, so page {pageIndex + 1} has no "
                + "rows to render and cannot exist - not a layout failure");

        Assert.That(ourPageCount, Is.GreaterThan(pageIndex),
            $"{referenceStem}: our render has {ourPageCount} page(s); the real-Crystal reference "
            + $"has at least {pageIndex + 1}, so page {pageIndex + 1} of content is missing entirely");

        using var ours = PDFtoImage.Conversion.ToImage(ourPdfStream, page: new Index(pageIndex));
        using var reference = SKBitmap.Decode(referencePngPath);

        Assert.That(ours, Is.Not.Null, "our PDF failed to rasterize");
        Assert.That(reference, Is.Not.Null, "reference PNG failed to decode");

        var (similarity, diff) = Compare(reference!, ours!);

        string outDir = Path.Combine(TestContext.CurrentContext.WorkDirectory, "visual-diffs");
        Directory.CreateDirectory(outDir);
        string diffPath = Path.Combine(outDir, $"{referenceStem}-page{pageIndex + 1}-diff.png");
        using (var fs = File.OpenWrite(diffPath))
            diff.Encode(fs, SKEncodedImageFormat.Png, 90);
        diff.Dispose();

        // Our own render, written beside the diff. The diff alone cannot be read: it marks
        // every pixel that differs, so a region present in one image and absent from the
        // other looks the same as one that is present in both and merely shifted. Having
        // the render itself is what makes a low score diagnosable.
        string oursPath = Path.Combine(outDir, $"{referenceStem}-page{pageIndex + 1}-ours.png");
        using (var fs = File.OpenWrite(oursPath))
            ours!.Encode(fs, SKEncodedImageFormat.Png, 90);

        double inkAgreement = InkAgreementPercent(reference!, ours!);

        TestContext.Out.WriteLine(
            $"{referenceStem} page {pageIndex + 1}: ink agreement {inkAgreement:F1}%, " +
            $"mean-pixel similarity {similarity:F1}% (not assertable — see InkAgreementPercent). " +
            $"Diff written to {diffPath}");

        string baselineKey = $"{referenceStem}/{pageIndex + 1}";
        Assert.That(InkAgreementBaseline.ContainsKey(baselineKey), Is.True,
            $"no recorded ink-agreement baseline for {baselineKey} — add one");
        double baseline = InkAgreementBaseline[baselineKey];

        Assert.That(inkAgreement, Is.GreaterThanOrEqualTo(baseline - BaselineTolerance),
            $"{referenceStem} page {pageIndex + 1}: ink agreement fell from a recorded {baseline:F1}% "
            + $"to {inkAgreement:F1}% — content that used to line up with the real-Crystal render "
            + $"no longer does. See {diffPath}");

        // Improvements are surfaced rather than silently absorbed, so the recorded baseline
        // keeps meaning something.
        Assert.That(inkAgreement, Is.LessThanOrEqualTo(baseline + 5.0),
            $"{referenceStem} page {pageIndex + 1}: ink agreement IMPROVED from {baseline:F1}% to "
            + $"{inkAgreement:F1}%. This is good — raise the recorded baseline to match.");
    }

    /// <summary>
    /// Reads a data fixture into the shape <see cref="RuntimeOverrides.Data"/> wants: one
    /// flattened table whose column names are the report's *raw* Crystal column names, which
    /// is what the fixture's header row holds.
    ///
    /// Columns are typed from their contents. Leaving everything a string was the earlier
    /// choice, on the reasoning that the engine converts from the RDL field types anyway —
    /// which is true of arithmetic and false of formatting. A textbox Format of
    /// "MM/dd/yyyy" over a value that arrived as the string "2001-05-26" does nothing at
    /// all, so with string columns this suite could not measure any formatting work, and
    /// reported no change from a conversion fix that was in fact reaching the right cell.
    /// </summary>
    private static DataTable LoadCsvFixture(string path)
    {
        var lines = File.ReadAllLines(path);
        var header = SplitCsvLine(lines[0]);
        var rows = lines.Skip(1).Where(l => l.Length > 0).Select(SplitCsvLine).ToList();

        var table = new DataTable();
        for (int c = 0; c < header.Count; c++)
            table.Columns.Add(header[c], InferColumnType(rows, c));

        foreach (var values in rows)
        {
            var row = table.NewRow();
            for (int i = 0; i < table.Columns.Count && i < values.Count; i++)
            {
                if (values[i].Length == 0) { row[i] = DBNull.Value; continue; }
                row[i] = table.Columns[i].DataType == typeof(DateTime)
                    ? DateTime.ParseExact(values[i], FixtureDateFormat, CultureInfo.InvariantCulture)
                    : table.Columns[i].DataType == typeof(double)
                        ? double.Parse(values[i], CultureInfo.InvariantCulture)
                        : values[i];
            }
            table.Rows.Add(row);
        }
        return table;
    }

    // The fixture builder writes dates in one unambiguous shape, so this asks for that shape
    // exactly rather than letting TryParse guess — "2001" is a perfectly good date to
    // DateTime.TryParse, and a column of years would silently become a column of midnights.
    private const string FixtureDateFormat = "yyyy-MM-dd";

    private static Type InferColumnType(List<List<string>> rows, int column)
    {
        var values = rows.Where(r => column < r.Count).Select(r => r[column])
            .Where(v => v.Length > 0).ToList();
        if (values.Count == 0) return typeof(string);
        if (values.All(v => DateTime.TryParseExact(v, FixtureDateFormat,
                CultureInfo.InvariantCulture, DateTimeStyles.None, out _)))
            return typeof(DateTime);
        if (values.All(v => double.TryParse(v, NumberStyles.Float,
                CultureInfo.InvariantCulture, out _)))
            return typeof(double);
        return typeof(string);
    }

    private static List<string> SplitCsvLine(string line)
    {
        var fields = new List<string>();
        var field = new System.Text.StringBuilder();
        bool inQuotes = false;
        for (int i = 0; i < line.Length; i++)
        {
            char ch = line[i];
            if (inQuotes)
            {
                if (ch == '"' && i + 1 < line.Length && line[i + 1] == '"') { field.Append('"'); i++; }
                else if (ch == '"') inQuotes = false;
                else field.Append(ch);
            }
            else if (ch == '"') inQuotes = true;
            else if (ch == ',') { fields.Add(field.ToString()); field.Clear(); }
            else field.Append(ch);
        }
        fields.Add(field.ToString());
        return fields;
    }

    /// <summary>
    /// Agreement between the two renders' *ink* — the fraction of non-white pixels the two
    /// images share, over the union of their non-white pixels (Jaccard index), after
    /// aligning dimensions.
    ///
    /// This is the assertable metric, and <see cref="Compare"/>'s mean-pixel-difference is
    /// not, because these pages are 2-9% ink on white. Scoring a *pure white image* against
    /// these six references with that formula gives 93.9-98.5% — above any useful floor —
    /// so it passes a completely blank render and cannot distinguish "rendered correctly"
    /// from "rendered nothing". Ink agreement is 0 for a blank render by construction.
    ///
    /// Compared at a coarse grid rather than per pixel: the two engines place glyphs at
    /// slightly different subpixel offsets, so exact ink pixels rarely coincide even when
    /// the content is identical. A cell counts as inked if any pixel in it is inked, which
    /// tolerates that shift while still requiring content in the same places.
    /// </summary>
    private static double InkAgreementPercent(SKBitmap reference, SKBitmap ours, int cell = 8)
    {
        using SKBitmap oursResized = (reference.Width == ours.Width && reference.Height == ours.Height)
            ? ours.Copy()
            : ours.Resize(new SKImageInfo(reference.Width, reference.Height), new SKSamplingOptions(SKFilterMode.Linear));

        using SKBitmap a = reference.Copy(SKColorType.Bgra8888);
        using SKBitmap b = oursResized.Copy(SKColorType.Bgra8888);
        byte[] aBytes = a.Bytes;
        byte[] bBytes = b.Bytes;

        int cols = (a.Width + cell - 1) / cell;
        int rows = (a.Height + cell - 1) / cell;
        var aInk = new bool[cols * rows];
        var bInk = new bool[cols * rows];

        for (int y = 0; y < a.Height; y++)
        {
            for (int x = 0; x < a.Width; x++)
            {
                int o = (y * a.Width + x) * 4;
                int cellIndex = (y / cell) * cols + (x / cell);
                // "Ink" = visibly darker than the paper, summed across B/G/R.
                if (765 - (aBytes[o] + aBytes[o + 1] + aBytes[o + 2]) > 90) aInk[cellIndex] = true;
                if (765 - (bBytes[o] + bBytes[o + 1] + bBytes[o + 2]) > 90) bInk[cellIndex] = true;
            }
        }

        int intersection = 0, union = 0;
        for (int i = 0; i < aInk.Length; i++)
        {
            if (aInk[i] && bInk[i]) intersection++;
            if (aInk[i] || bInk[i]) union++;
        }
        return union == 0 ? 100.0 : 100.0 * intersection / union;
    }

    /// <summary>
    /// Aligns dimensions (resizing our render to the reference's size — real-Crystal PDFs
    /// and ours may come out at slightly different default page-to-pixel scaling), then
    /// computes a per-pixel RGB difference. Retained only for the red-heat diff image used
    /// in human triage: see <see cref="InkAgreementPercent"/> for why its score is not
    /// suitable as a pass criterion.
    /// </summary>
    private static (double SimilarityPercent, SKBitmap Diff) Compare(SKBitmap reference, SKBitmap ours)
    {
        using SKBitmap oursResized = (reference.Width == ours.Width && reference.Height == ours.Height)
            ? ours.Copy()
            : ours.Resize(new SKImageInfo(reference.Width, reference.Height), new SKSamplingOptions(SKFilterMode.Linear));

        SKBitmap a = reference.Copy(SKColorType.Bgra8888);
        SKBitmap b = oursResized.Copy(SKColorType.Bgra8888);
        var diff = new SKBitmap(new SKImageInfo(a.Width, a.Height, SKColorType.Bgra8888));

        byte[] aBytes = a.Bytes;
        byte[] bBytes = b.Bytes;
        byte[] diffBytes = new byte[aBytes.Length];

        long totalDiff = 0;
        int pixelCount = a.Width * a.Height;
        for (int i = 0; i < pixelCount; i++)
        {
            int o = i * 4; // B, G, R, A (Bgra8888)
            int db = Math.Abs(aBytes[o] - bBytes[o]);
            int dg = Math.Abs(aBytes[o + 1] - bBytes[o + 1]);
            int dr = Math.Abs(aBytes[o + 2] - bBytes[o + 2]);
            int d = db + dg + dr;
            totalDiff += d;

            byte intensity = (byte)Math.Min(255, d);
            diffBytes[o] = 0;              // B
            diffBytes[o + 1] = 0;          // G
            diffBytes[o + 2] = intensity;  // R — brighter red = more different
            diffBytes[o + 3] = 255;        // A
        }

        System.Runtime.InteropServices.Marshal.Copy(diffBytes, 0, diff.GetPixels(), diffBytes.Length);

        double maxPossibleDiff = (double)pixelCount * 255 * 3;
        double similarity = 100.0 * (1.0 - totalDiff / maxPossibleDiff);

        a.Dispose();
        b.Dispose();
        return (similarity, diff);
    }
}
