using System.Data;
using System.Globalization;
using System.Linq;
using Majorsilence.Crystal.RptEngine;
using Majorsilence.Crystal.Runtime;
using SkiaSharp;

namespace Majorsilence.Crystal.VisualRegression.Tests;

/// <summary>
/// Compares majorsilence.crystal's own PDF render against a checked-in ground-truth
/// screenshot from the real, licensed Crystal Reports engine (tests/reference-renders/,
/// generated by tools/Majorsilence.Crystal.ReferenceRenderer on a dev machine that has
/// that engine installed — see this repo's plan notes).
///
/// Exact pixel equality is not the goal and never will be: the real engine renders via
/// GDI+, ours via SkiaSharp through a different RDL layout engine, so font hinting and
/// subpixel placement differ even when everything is semantically right. What is asserted
/// is <see cref="InkAgreementPercent"/> against a recorded per-case baseline — see that
/// method for why the mean-pixel score it sits beside is *not* assertable.
///
/// These cases can only be as good as the data behind them. The reference images were
/// rendered from the rows saved inside each .rpt, which this pipeline cannot read, so a
/// case with no fixture in tests/reference-data/ renders with no rows and scores ~0 no
/// matter how correct the layout is. Fixtures come from those same saved rows, in two
/// dev-machine-only steps:
///
///   ReferenceRenderer --xls  &lt;report&gt;.rpt  &lt;report&gt;.xls
///   FixtureBuilder           &lt;report&gt;.rpt  &lt;report&gt;.xls  tests/reference-data/&lt;report&gt;.csv
///
/// Only reports whose detail rows survive that export have one; a report that shows only
/// group summaries or a cross-tab does not, and cannot until the saved-data stream itself
/// can be read. BACKLOG.md has the details.
/// </summary>
[TestFixture]
public class VisualRegressionTests
{
    /// <summary>
    /// Measured ink-agreement baselines, asserted as "no worse than", with an improvement
    /// also failing so the number cannot drift up unnoticed and stop meaning anything.
    ///
    /// The zeros are cases with no data fixture: the DataSet's CommandText is a SQL query
    /// against a data source that does not exist at test time, so nothing data-bound
    /// renders and no amount of layout work can move them. Those three report only
    /// aggregates or a cross-tab, and Crystal's data-only export gives what a report
    /// displays, so their detail rows are not obtainable that way — see BACKLOG.
    ///
    /// CustomerList went 1.5% → 8.9% on getting a fixture, → 15.0% on reading the
    /// report's real page size (it is landscape, and was being rendered portrait),
    /// → 16.2% on stopping the table from synthesizing a header row of column names,
    /// and → 28.9% on giving the table its real geometry: columns as wide as the gap to
    /// the next one, and a page margin of a sixth of an inch rather than a half.
    ///
    /// It then went *down* to 28.4% on reading text alignment correctly, which is worth
    /// spelling out because it looks like a regression and is not. Left-aligned, this
    /// report's title printed on top of the logo, so it cost nothing: those cells were
    /// inked in both images anyway. Centred - which is where Crystal puts it, within 70
    /// pixels - it moves off the logo and inks cells of its own, at a height the
    /// reference does not have a title at, because our whole header block still sits
    /// about four tenths of an inch too low. The metric is charging the alignment fix for
    /// a section-ordering bug that was already there; see BACKLOG.
    ///
    /// → 35.0% on a table band's contents being positioned against the table rather
    /// than the page. Its column labels ran 0.08in past the end of the table holding them.
    ///
    /// → 34.8% on the engine drawing images at the size their report item asks for
    /// rather than a third larger, which is where its logo went.
    ///
    /// → 32.4% once that section-ordering bug was fixed: Crystal prints the Report
    /// Header above the Page Header on page one, and RDL's PageHeader cannot, so the page
    /// header moved into the table's own Header band. The title and logo now sit at the
    /// top of the page with the column labels below them, which is the arrangement the
    /// reference has.
    ///
    /// SalesByCustomer-Grouped went 3.6% to 3.7% on its group-header labels being emitted
    /// once instead of twice, then to 20.6% - its largest jump - on the report header
    /// getting a full-width table of its own instead of riding inside the details table,
    /// which is narrower than the page and indented to its first column. The title and
    /// logo now start at the top left corner, where Crystal has them. Then to 32.4% on the
    /// engine's image sizing: its logo was being drawn a third oversized, over the start of
    /// the title.
    ///
    /// SalesByCustomer-Grouped is the second case with a fixture and the first grouped
    /// one. It renders the right structure — group header, detail row, subtotal, a page
    /// break per group — so its number is low for real remaining reasons rather than for
    /// want of data.
    ///
    /// Top5USAsubCanada has no fixture and still scores above zero, because its report
    /// header and footer are static and now land where Crystal puts them.
    ///
    /// Five cases were added at once when the fixture route was swept across the whole
    /// public corpus. They divide sharply, and the division is the useful part.
    ///
    /// Country-Region-Sort (28.7%) and boyum__SampleReport (37.1%) - the best score in the
    /// suite, and the first case here from a different report author - render about as much
    /// ink as their references do (5.5% against 5.3%, 0.7% against 0.6%). They are ordinary
    /// list reports and what is left between them and 100% is placement, not content.
    ///
    /// Then a twip written exactly, and the engine rounding instead of truncating - two
    /// halves of one arithmetic error, and together the largest movement this suite has
    /// ever recorded. **Country-Region-Sort 62.3 -> 94.9%, Orders5-150 60.0 -> 87.2%,
    /// ProductPriceList 63.6 -> 83.9%, Orders10k 74.6 -> 87.3%, ProductPriceList-xs
    /// 59.9 -> 78.5%, CustomerList 90.6 -> 98.6%.**
    ///
    /// Country-Region-Sort is what exposed it: page after page that looked *identical* to
    /// the reference and scored 62%. Its rows start aligned with Crystal's and end 13px
    /// above them, a quarter of a pixel per row. TwipsToRdl emitted inches to three decimal
    /// places, and a thousandth of an inch is 0.3px at 300dpi - on a table row that loss is
    /// not a one-off but a pitch. Inches cannot be fixed by adding digits either: a twip is
    /// 1/1440in, whose decimal expansion repeats. Points can - a twip is exactly 0.05pt.
    ///
    /// Emitting points alone made two reports WORSE, and that was the interesting half. The
    /// engine's RSize stored sizes as integer parts of 1/2540in using a truncating cast, so
    /// every dimension came out up to one part short, always downward. A 289-twip row is
    /// 509.76 parts, truncated to 509, where Crystal's own pitch rounds to 510 - and the old
    /// three-decimal rounding had been overshooting just enough to land on 510 by accident.
    /// Exact input removed the accident and exposed the truncation. Rounding in RSize (in
    /// the Reporting repo) is the other half, and with both, everything moves together.
    ///
    /// boyum__SampleReport 81.1 -> 75.0 is the one case that goes down and stays down. Its
    /// whole content block sits 3-4px low at a constant offset with the row pitch exact, so
    /// the truncation bias had been cancelling a different, pre-existing defect. Recorded at
    /// its measured value and raised as its own issue rather than papered over.
    ///
    /// Then a detail field sitting at its own Top inside its row. **BeforeTV 75.3 -> 86.4%**,
    /// the second largest single move this suite has recorded, from a change that had been
    /// written off here as worth about three pixels.
    ///
    /// It is not a per-object error, it is a per-row one. A detail band is one row as tall as
    /// the whole section and its objects sit at their own Top inside it; written as plain
    /// cells they were all flushed to the top. BeforeTV draws its middle field 68 twips down
    /// a 289-twip band, and flushing it collapsed every row's ink into a **33-37px band where
    /// the real engine draws 45-46px**. With each cell given the object's own vertical box,
    /// every one of BeforeTV's row bands lands within 1px of the reference, at identical
    /// heights and an identical 60px pitch.
    ///
    /// SalesByCustomer-Grouped 64.4 -> 64.8 for the same reason, smaller because its detail
    /// objects sit only 15 twips down. Nothing else in the suite moves and nothing drops.
    ///
    /// Then a band cell's border and background belonging to the object rather than to the
    /// cell. **SalesByCustomer-Grouped 61.4 -> 64.4%.**
    ///
    /// Crystal draws each column label's underline across that label's own width. Ours drew
    /// one continuous rule, because a border belongs to the cell and the padding added in
    /// the previous entry insets only the text inside it. Measured at 300dpi, the rule ran
    /// x 791-1888 - which is the Order Amount column's left edge and the Date column's right
    /// edge, a picture of the table rather than of the report.
    ///
    /// A band cell's object now goes in a Rectangle as a Textbox at its own Left/Top/Width/
    /// Height, which is how the report header and page footer bands in the same table were
    /// already written. The two underlines come out 300px and 251px against Crystal's 305
    /// and 256, and the group-footer subtotal's grey box 545px against 558 - it had been
    /// 737px, the full column.
    ///
    /// The open question when the padding was chosen instead was what this engine does with
    /// a Textbox wider than its cell, since Crystal's group caption is often as wide as the
    /// whole band and simply overlaps the labels further across. Answered: Rectangle.RunPage
    /// offsets its children and does not clip them, so the 11,340-twip caption is emitted at
    /// full width in a 3,498-twip cell and overlaps rightward the way Crystal does. Its ink
    /// spans x 65-575 against the reference's 65-579, uncut. No clamp was needed. What is
    /// still untested is a caption that is both oversized and carries a background - no
    /// public report has one, so the paint order over neighbouring cells is unobserved.
    ///
    /// Still out by a little vertically: the header band's underlines sit 6px above
    /// Crystal's and the detail row 8px above, and the subtotal box renders 47px tall
    /// against Crystal's 43 - the object's own height is 263 twips, so Crystal is drawing
    /// that box to something other than the object's bounds. Band-height questions, untouched.
    ///
    /// Then the report no longer declaring a culture it was only ever told about numbers.
    /// Every fixture-backed case moved and none went down - CustomerList 90.2 -> 90.6,
    /// boyum__SampleReport 80.5 -> 81.1, ProductPriceList 63.3 -> 63.6, Orders10k 74.4 ->
    /// 74.6, and a tenth or two each on the rest.
    ///
    /// The .rpt's number separators were being emitted as RDL's report-level Language, which
    /// is the whole report's culture and takes dates with it. Country-Region-Sort's print
    /// date is Format(ExecutionTime, "d") - the machine's own short date pattern - and the
    /// real engine renders 2026-08-28 on this box where we rendered 9/11/2026 from the same
    /// run. The separators now go on the styles of the numeric objects that need them, and
    /// the report names no culture, so the engine falls back to CultureInfo.CurrentCulture:
    /// the machine, which is what Crystal defers to. See RdlConverter.NeedsSeparatorCulture.
    ///
    /// A side benefit for this suite: that field renders today's date against a reference
    /// rendered on a fixed day, so it never matches - but an ISO date is the same width
    /// every day, where M/d/yyyy was not, and the case no longer drifts with the calendar.
    ///
    /// Then a group band's objects sitting where the report drew them. **SalesByCustomer
    /// -Grouped 54.0 -> 61.2%**, its largest move since it got a header table of its own,
    /// and the only case here with a group band and a data fixture.
    ///
    /// Four faults in one band, each measured off the reference before it was touched. Its
    /// caption rendered 14% narrower than Crystal draws it, which looks like the font
    /// metrics story above and is not: the caption is a FieldObject, only the TextObject
    /// case was read, and with nothing found the format fell back to a synthesized
    /// { Bold = true } - the right words in a font the report never asked for. Its caption
    /// then sat a third of an inch right of Crystal's, because the table's lead column
    /// exists precisely so a band can reach left of the first data column and the group row
    /// skipped it unconditionally. Its "Order Amount" label sat three quarters of an inch
    /// left of Crystal's, at its column's start rather than 1,122 twips into it. And the
    /// whole band sat 26 pixels high, every object flushed to the top of a row as tall as
    /// the section instead of sitting at its own Top.
    ///
    /// With all four fixed every glyph run in that band lands within 2px of the reference,
    /// horizontally and vertically, where the caption had been 99px out. 27 of the 88 public
    /// reports and 1,360 of the 2,324 private ones emit different RDL.
    ///
    /// What is left there is the one thing a table cell cannot express: Crystal draws the
    /// two column-label underlines across each label's own width, 305px and 256px, and ours
    /// draws one continuous 1,098px rule, because a border belongs to the cell and padding
    /// moves only the text inside it. The grey subtotal box is wider than Crystal's for the
    /// same reason. Both want the object wrapped in a Rectangle at its own Left and Width,
    /// which is how the report header and page footer bands already work. See BACKLOG.
    ///
    /// Then a date field that defers to the machine, which was being given a fixed format.
    /// **Orders10k 61.1 -> 74.4%, Orders5-150 49.1 -> 59.9%** - the column the previous entry
    /// named as that report's remaining problem.
    ///
    /// Crystal's CSV export writes rendered values, so it hands back a formatted date as a
    /// string and a record's bytes can be paired with what the real engine does with them.
    /// Seven public reports display a date field; these two come back as
    /// "2000-12-02  12:00:00AM" where SalesByCustomer-Grouped gives "05/26/2001" from the
    /// same column of the same sample database. The difference is bytes[2] and bytes[3] of
    /// the format record, 0,0 on these and 1,1 there, and 0,0 means no date components are
    /// configured - the field takes the machine's short date.
    ///
    /// So the fix is to emit no format rather than a better one. The ISO look of that string
    /// is this machine, which runs en-CA; writing it out as a format would have baked the
    /// converting machine's locale into every report. An existing test said exactly that
    /// about a neighbouring case and caught the attempt. Our engine and Crystal both fall
    /// back to the machine for an unformatted date, so the two now agree by deferring rather
    /// than by matching a constant.
    ///
    /// Then the 11% that had been written down as this suite's ceiling, which was a defect
    /// here all along, and fixing it moved these numbers further than everything before it
    /// put together. **CustomerList 61.0 -> 90.2%, boyum__SampleReport 57.0 -> 80.5%,
    /// BeforeTV 57.4 -> 75.1%.**
    ///
    /// Crystal's font size is a character cell height and RDL's FontSize is an em, and this
    /// converter was emitting one as the other. Crystal's own PDF export says so outright:
    /// a 10pt Arial object is written "8.95 Tf". See RdlConverter.EmPointsFor.
    ///
    /// Every one of the 88 public reports and 2,316 of the 2,324 private ones emit different
    /// RDL, which makes this the widest change measured here by a wide margin. Two cases go
    /// down. Orders5-150 51.1 -> 49.1 is the only one outside tolerance and its glyph widths
    /// now match the reference to within 1.5% across six measured strings - what is left is
    /// a date column reading 12/02/2000 where Crystal renders 2000-12-02 next to a separate
    /// 12:00, and with the text finally the right size that column is most of what the
    /// report still disagrees about. SalesByCustomer-Grouped 54.8 -> 54.0 is within
    /// tolerance and recorded as measured.
    ///
    /// Then Crystal's Highlighting Expert, which had been written down twice as not worth
    /// attempting and was wrong about why. SalesByCustomer-Grouped 48.3 -> 54.8%, its second
    /// largest move. Its page 1 carries one detail row and one subtotal, so the subtotal
    /// being red on grey where ours was black on white was most of what was left to disagree
    /// about.
    ///
    /// The reason it became attemptable is that a measurable case existed after all. The
    /// rules live in tag-191 records and the operator codes are the whole problem: one
    /// sample cannot tell "less than" from "not equal", and a rule applied with the wrong
    /// comparison highlights the wrong rows, which is worse output than none.
    /// USA-Orders-RWB-colored settles it - a single rule, operator 5, threshold 100000.00,
    /// and the real engine renders every one of its 20 state subtotals above $100,000 green
    /// and every one below in the object's own colour. That also fixes the channel order:
    /// the rule's colour bytes are 00 00 80 00, and read as flag,B,G,R those are exactly the
    /// #008000 on the page.
    ///
    /// 3 of the 88 public reports change and none of the 2,324 private ones do - the third
    /// public one is Top5USAwithSub, whose subreport is the same content as RWB. Almost
    /// every tag-191 record in either corpus is empty: 678 of them across 117 private files,
    /// all zero-length, an object carrying the feature's slot with no rules in it.
    ///
    /// Then a numeric field's format applying at all, which was a defect this suite was too
    /// coarse to catch when it shipped. ProductPriceList's Product ID rendered "$1,101"
    /// against Crystal's "1101" and the report still scored 59.6% - in line with its peers,
    /// so nothing looked wrong. Both its numeric fields store a "$" and a "," thousands
    /// separator and Crystal honours neither on the ID, which is what identified data[4] in
    /// the format record as the flag deciding whether the symbol and the grouping apply.
    /// ProductPriceList 59.6 -> 62.8. Five of the 88 public reports and 111 of the private
    /// corpus's 2,324 emit different RDL for it, each gaining exactly one bare format.
    ///
    /// ProductPriceList-xs entered at 33.8%, half its sibling, and went to 59.5% on the
    /// detail columns being sorted left to right. A detail band's objects are recorded in
    /// the order the report was authored, not the order they are drawn: this report records
    /// Price, its rightmost column, in front of the one to its left. Columns, widths and
    /// cells were all built in that order, so two things went wrong at once - the values
    /// came out in the wrong columns, and the non-ascending starts tripped the guard on the
    /// gap-based widths, which fell back to each object's own width and closed every gap in
    /// the row, dragging the whole band left cumulatively. One sort fixes both.
    ///
    /// It is the only fixture-backed report with an out-of-order detail band, so nothing
    /// else in this suite moves - but 33 of the 88 public reports and 1,627 of the private
    /// corpus's 2,324 emit different RDL, which is the widest change this suite has
    /// measured. See BACKLOG.
    ///
    /// boyum__SampleReport then went 37.1% -> 38.4% on a band no longer being clamped to
    /// its table's left edge. Its print date sits at the page margin, an inch and a third
    /// left of the first data column, and came out printed on top of that column's heading.
    ///
    /// ProductPriceList joined at 59.6% once its fixture stopped losing rows. 39 of its 115
    /// products have no Color, and a BIFF row omits an empty cell, so those rows exported
    /// four values instead of five and were dropped as short - the fixture held 76 rows and
    /// the report renders 115. Placing values by column index rather than compacting them
    /// recovers all of them; see BACKLOG.
    ///
    /// Then the drop shadow, which RDL has no property for and which was left unimplemented
    /// twice before on grounds of proportion. Measured off the reference at 300dpi it is an
    /// 11px strip about 15px down and right of the box, so it goes out as the two visible
    /// strips rather than one rectangle behind a transparent object. SalesByCustomer-Grouped
    /// 42.5 -> 48.3, its second largest move, and the four worst-agreeing bands on the page
    /// were all this. Exactly one object in the whole public corpus has the flag.
    ///
    /// Then the report declaring its own Language, which nudged three cases by a tenth or
    /// two (CustomerList 60.9 -> 61.0, Orders10k 57.1 -> 57.2, SalesByCustomer-Grouped
    /// 42.3 -> 42.5). The engine formats numbers and dates with the rendering machine's
    /// culture unless the report names one, so those numbers were never wrong here - this
    /// host is en-US - but they were only right by accident. See BACKLOG.
    ///
    /// Then the numeric format - decimal places and the currency symbol, from the second of
    /// the two tag-249 records each object carries. SalesByCustomer-Grouped 41.7 -> 42.3:
    /// both its amounts read $53.90 instead of 53.9. Only that report has a fixture with a
    /// currency field, so nothing else moves.
    ///
    /// Then object borders: what the report draws as a box around its title, a rule under
    /// a column label, or a frame around a subtotal is border formatting on the object -
    /// tag 237 in the file - not a line object. SalesByCustomer-Grouped 34.0 -> 41.7, its
    /// largest single move, and the first change to touch it since its own header table.
    /// Nothing else moves because no other fixture-backed report uses borders.
    ///
    /// Then the engine's point: it converted inches to points with 72.27 - TeX's printer's
    /// point - where PDF, CSS and GDI all define 1pt = 1/72in. Every dimension written in
    /// inches came out 0.375% oversized: a Letter page had a MediaBox of 794x614 instead of
    /// 612x792, and CustomerList's 0.215in rows rendered 15.535pt tall instead of 15.48,
    /// a pitch error that put its rows half a cell adrift by the bottom of the page. Fixed
    /// in Majorsilence.Reporting (RSize). CustomerList 57.6 -> 60.9 - its rows now sit on
    /// Crystal's - while Country-Region-Sort 64.4 -> 60.9 and SampleReport 58.3 -> 57.1.
    /// Those two dips are quantisation, not movement: at 24px cells both are unchanged
    /// (88.0 and 86.5), and the render is now on a correctly-sized page with exact row
    /// pitch, so the 8px numbers resettle around sub-cell boundaries. All recorded at
    /// measured values.
    ///
    /// Then the font style bits, and this one moved two of them DOWN, which is worth
    /// spelling out. The parser read 0x02 as italic and 0x04 as underline; neither bit is
    /// ever set in either corpus, so both attributes were dead. The bits the files use are
    /// 0x1 and 0x10000, and with those the column headings underline where Crystal
    /// underlines them. CustomerList 57.2 -> 57.6, but Country-Region-Sort 64.6 -> 64.4 and
    /// SampleReport 59.2 -> 58.3. The text does not move at all - the renders differ by 48
    /// bytes of stroke. That dip was first blamed on the stroke being drawn 7px low and the
    /// width of the textbox; measuring the ink bands showed both claims false. Each rule
    /// sits 2-3px under its own glyphs and is a few px wider than them, in both renders.
    /// What differs is the glyphs: for the same string in the same nominal font ours is
    /// about 11% wider, and ours is the one matching Arial's published metrics.
    /// *(That was read as a renderer difference capping what this suite could reach. It was
    /// a defect in this converter, and it is fixed - see the entry below. Ours did match
    /// Arial's published em metrics; the em was the wrong measurement to match.)*
    ///
    /// Then a detail cell padded back to the width of the field the report drew, rather
    /// than filling a column that is as wide as the gap to the next one: Country-Region-Sort
    /// 61.0 -> 64.6, CustomerList 55.1 -> 57.2, SalesByCustomer-Grouped 33.9 -> 34.7. A
    /// right-aligned number had been ending flush against the next column's first word.
    ///
    /// Then the big one: a detail cell no longer grows. Crystal's Can Grow is a per-object
    /// flag that is off by default, and writing CanGrow=true on every table cell threw away
    /// the row height taken from the object's own bounds. In a table that is not a one-off
    /// error but a row pitch - our rows came out 53.5px apart against Crystal's 46px, a
    /// third of an inch of drift by the thirteenth row. Country-Region-Sort 29.8 -> 59.6,
    /// SampleReport 38.7 -> 59.1, CustomerList 36.7 -> 55.1, the largest movement this
    /// suite has recorded. Reports without a fixture cannot show it, and the grouped report
    /// does not move because its own remaining faults are elsewhere.
    ///
    /// Every fixture-backed case had already moved at once - CustomerList 35.0 -> 36.7,
    /// SalesByCustomer-Grouped 32.4 -> 33.9, Country-Region-Sort 28.7 -> 29.8,
    /// SampleReport 38.4 -> 38.7 - on a page footer of Crystal special fields staying in
    /// RDL's own PageFooter instead of being routed into the details table. The table's
    /// footer band renders where the table ends; a page footer belongs at the foot of the
    /// page, which is where Crystal puts it and where these references now go.
    ///
    /// BeforeTV, Orders10k and Orders5-150 rendered almost blank pages for a long time -
    /// 0.14% ink against references carrying 2.3-8.0%. All three have a record-selection
    /// formula testing a field against a report parameter, which is how Crystal spells a
    /// range - {Orders.Order Amount} = {?Order_Amt_Range}. It converts faithfully to an RDL
    /// DataSet Filter, and then no parameter value exists at render time, so the comparison
    /// was false for every row and the report selected nothing. Making an unanswered
    /// parameter inert rather than exclusive took them to 57.4%, 57.1% and 51.1% - the
    /// largest movement in this suite's history, and the three of them had been the largest
    /// remaining gap in it.
    ///
    /// TenPct-DiscountDays is ProductPriceList's rows with one computed column - its price
    /// times 0.9 - which the fixture deliberately leaves out, so the engine has to evaluate
    /// the formula per row. It is the only case with a formula in its detail section. Its
    /// first reference scored 25.5% because it was rendered over Remote Desktop, whose
    /// redirected printer moved Crystal's whole page 6pt in on every edge; rendered against
    /// the printer every other reference used, it is 74.3%.
    ///
    /// A formula object's numeric format was always dropped, because the file does not
    /// record a formula's result type and every object carries a numeric record, the ones
    /// showing strings included. Deciding the type from the formula's text where it is not in
    /// doubt took TenPct-DiscountDays 74.3 -> 76.8, its computed column now "$13.05" where it
    /// was "13.05", and BeforeTV 85.8 -> 86.5, whose report-footer Sum formula now prints
    /// "$52,263.63" as Crystal's does.
    ///
    /// Then every right-aligned amount moved 2.6pt left, and five cases moved 5-12 points:
    /// **TenPct-DiscountDays 76.8 -> 88.4, ProductPriceList 83.9 -> 92.8, BeforeTV 86.5 ->
    /// 95.2, ProductPriceList-xs 78.5 -> 86.5, Orders10k 87.3 -> 92.6, Orders5-150 87.2 ->
    /// 91.3.** A value formatted with its own currency format ends in a space in Crystal's
    /// text - its PDF has a real space glyph after "$14.50" - so it stops a space short of
    /// its object's right edge, and ours ran on to the edge. Measured with both engines' PDF
    /// text positions, those columns went from +2.60pt to +0.10pt of Crystal's, which is
    /// what the left-aligned columns already were.
    /// </summary>
    private static readonly Dictionary<string, double> InkAgreementBaseline = new()
    {
        ["benbrahim777__CustomerList/1"] = 98.6,
        ["benbrahim777__SalesByCustomer-Grouped/1"] = 65.1,
        ["benbrahim777__Top5USAsubCanada/1"] = 2.9,
        ["benbrahim777__Canada-CrossTab/1"] = 0.1,
        ["benbrahim777__Top5USA-piechart/1"] = 0.0,
        ["benbrahim777__Top5USAsubCanada/2"] = 0.0,
        ["benbrahim777__Country-Region-Sort/1"] = 94.9,
        ["boyum__SampleReport/1"] = 75.0,
        ["benbrahim777__ProductPriceList/1"] = 92.8,
        ["benbrahim777__ProductPriceList-xs/1"] = 86.5,
        ["benbrahim777__BeforeTV/1"] = 95.2,
        ["benbrahim777__Orders10k/1"] = 92.6,
        ["benbrahim777__Orders5-150/1"] = 91.3,
        ["benbrahim777__TenPct-DiscountDays/1"] = 88.4,
    };

    // Slack below the recorded baseline, for anti-aliasing and font-hinting jitter between
    // runs. Small on purpose: the baselines are near zero, so a real drop is still visible.
    private const double BaselineTolerance = 1.0;

    [OneTimeSetUp]
    public void Init() => ReportEngine.Init();

    private static string CorpusPath(string name) =>
        Path.GetFullPath($"../../../../rpt-corpus/{name}", AppContext.BaseDirectory);

    private static string ReferencePath(string corpusStem, int pageIndex) =>
        Path.GetFullPath(
            $"../../../../reference-renders/{corpusStem}/real-crystal-page-{pageIndex + 1}.png",
            AppContext.BaseDirectory);

    [TestCase("benbrahim777__CustomerList.rpt", "benbrahim777__CustomerList", 0)]
    [TestCase("benbrahim777__SalesByCustomer-Grouped.rpt", "benbrahim777__SalesByCustomer-Grouped", 0)]
    [TestCase("benbrahim777__Top5USAsubCanada.rpt", "benbrahim777__Top5USAsubCanada", 0)]
    [TestCase("benbrahim777__Top5USAsubCanada.rpt", "benbrahim777__Top5USAsubCanada", 1)]
    [TestCase("benbrahim777__Canada-CrossTab.rpt", "benbrahim777__Canada-CrossTab", 0)]
    [TestCase("benbrahim777__Top5USA-piechart.rpt", "benbrahim777__Top5USA-piechart", 0)]
    [TestCase("benbrahim777__Country-Region-Sort.rpt", "benbrahim777__Country-Region-Sort", 0)]
    [TestCase("benbrahim777__Orders5-150.rpt", "benbrahim777__Orders5-150", 0)]
    [TestCase("benbrahim777__Orders10k.rpt", "benbrahim777__Orders10k", 0)]
    [TestCase("benbrahim777__BeforeTV.rpt", "benbrahim777__BeforeTV", 0)]
    [TestCase("boyum__SampleReport.rpt", "boyum__SampleReport", 0)]
    [TestCase("benbrahim777__ProductPriceList.rpt", "benbrahim777__ProductPriceList", 0)]
    [TestCase("benbrahim777__ProductPriceList-xs.rpt", "benbrahim777__ProductPriceList-xs", 0)]
    [TestCase("benbrahim777__TenPct-DiscountDays.rpt", "benbrahim777__TenPct-DiscountDays", 0)]
    public async Task ExportedPdf_MatchesRealCrystalReference(string corpusFile, string referenceStem, int pageIndex)
    {
        string rptPath = CorpusPath(corpusFile);
        Assume.That(File.Exists(rptPath), Is.True, $"{corpusFile} not found — run scripts/download-test-rpts.sh");

        string referencePngPath = ReferencePath(referenceStem, pageIndex);
        Assume.That(File.Exists(referencePngPath), Is.True, $"Reference image not found: {referencePngPath}");

        // The reference was rendered from the rows saved inside the .rpt, which this
        // pipeline cannot read (see BACKLOG). Where a data fixture exists — exported from
        // those same saved rows by ReferenceRenderer --xls and FixtureBuilder — push it, so
        // the two renders are actually comparable. Without one the render has no rows at all
        // and every data-bound item comes out empty.
        var overrides = new RuntimeOverrides();
        string dataFixturePath = Path.GetFullPath(
            $"../../../../reference-data/{referenceStem}.csv", AppContext.BaseDirectory);
        if (File.Exists(dataFixturePath))
            overrides.Data = LoadCsvFixture(dataFixturePath);

        byte[] pdfBytes;
        using (var rpt = File.OpenRead(rptPath))
        {
            pdfBytes = await new ReportEngine().ExportAsync(rpt, overrides, ExportFormat.Pdf);
        }

        using var ourPdfStream = new MemoryStream(pdfBytes);
        // A missing page is itself a finding worth naming, rather than an
        // ArgumentOutOfRangeException from the rasterizer.
        int ourPageCount = PDFtoImage.Conversion.GetPageCount(ourPdfStream, leaveOpen: true);
        ourPdfStream.Position = 0;

        // A page only exists if there are rows to fill it. With no data fixture the report
        // renders whatever is static and stops, so a reference page beyond ours says
        // something about the missing data rather than about layout - skip rather than fail,
        // and the case goes live the moment that report gets a fixture. Where a fixture DOES
        // exist a short render is a real defect and still fails.
        //
        // Top5USAsubCanada's second page is the case this exists for, and it is out of reach
        // twice over: the report has no fixture, and that page is a subreport, which
        // RuntimeOverrides.Data would not reach even with one - ReportEngine pushes only to
        // the main report's own DataSet1. It had been failing this suite continuously.
        // Ignore rather than Assume: an inconclusive result drops the case out of the run
        // entirely, where an ignored one stays visible in the count as a skip.
        if (overrides.Data is null && ourPageCount <= pageIndex)
            Assert.Ignore($"{referenceStem}: no data fixture, so page {pageIndex + 1} has no "
                + "rows to render and cannot exist - not a layout failure");

        Assert.That(ourPageCount, Is.GreaterThan(pageIndex),
            $"{referenceStem}: our render has {ourPageCount} page(s); the real-Crystal reference "
            + $"has at least {pageIndex + 1}, so page {pageIndex + 1} of content is missing entirely");

        using var ours = PDFtoImage.Conversion.ToImage(ourPdfStream, page: new Index(pageIndex));
        using var reference = SKBitmap.Decode(referencePngPath);

        Assert.That(ours, Is.Not.Null, "our PDF failed to rasterize");
        Assert.That(reference, Is.Not.Null, "reference PNG failed to decode");

        var (similarity, diff) = Compare(reference!, ours!);

        string outDir = Path.Combine(TestContext.CurrentContext.WorkDirectory, "visual-diffs");
        Directory.CreateDirectory(outDir);
        string diffPath = Path.Combine(outDir, $"{referenceStem}-page{pageIndex + 1}-diff.png");
        using (var fs = File.OpenWrite(diffPath))
            diff.Encode(fs, SKEncodedImageFormat.Png, 90);
        diff.Dispose();

        // Our own render, written beside the diff. The diff alone cannot be read: it marks
        // every pixel that differs, so a region present in one image and absent from the
        // other looks the same as one that is present in both and merely shifted. Having
        // the render itself is what makes a low score diagnosable.
        string oursPath = Path.Combine(outDir, $"{referenceStem}-page{pageIndex + 1}-ours.png");
        using (var fs = File.OpenWrite(oursPath))
            ours!.Encode(fs, SKEncodedImageFormat.Png, 90);

        // And the PDF it came from. Rasterising throws away where each piece of text sits;
        // the PDF keeps it, and Crystal's own PDF (ReferenceRenderer --pdf) is the other half
        // of that comparison - position to a fraction of a point, rather than to a pixel.
        File.WriteAllBytes(Path.Combine(outDir, $"{referenceStem}-ours.pdf"), pdfBytes);

        double inkAgreement = InkAgreementPercent(reference!, ours!);

        TestContext.Out.WriteLine(
            $"{referenceStem} page {pageIndex + 1}: ink agreement {inkAgreement:F1}%, " +
            $"mean-pixel similarity {similarity:F1}% (not assertable — see InkAgreementPercent). " +
            $"Diff written to {diffPath}");

        string baselineKey = $"{referenceStem}/{pageIndex + 1}";
        Assert.That(InkAgreementBaseline.ContainsKey(baselineKey), Is.True,
            $"no recorded ink-agreement baseline for {baselineKey} — add one");
        double baseline = InkAgreementBaseline[baselineKey];

        Assert.That(inkAgreement, Is.GreaterThanOrEqualTo(baseline - BaselineTolerance),
            $"{referenceStem} page {pageIndex + 1}: ink agreement fell from a recorded {baseline:F1}% "
            + $"to {inkAgreement:F1}% — content that used to line up with the real-Crystal render "
            + $"no longer does. See {diffPath}");

        // Improvements are surfaced rather than silently absorbed, so the recorded baseline
        // keeps meaning something.
        Assert.That(inkAgreement, Is.LessThanOrEqualTo(baseline + 5.0),
            $"{referenceStem} page {pageIndex + 1}: ink agreement IMPROVED from {baseline:F1}% to "
            + $"{inkAgreement:F1}%. This is good — raise the recorded baseline to match.");
    }

    /// <summary>
    /// Reads a data fixture into the shape <see cref="RuntimeOverrides.Data"/> wants: one
    /// flattened table whose column names are the report's *raw* Crystal column names, which
    /// is what the fixture's header row holds.
    ///
    /// Columns are typed from their contents. Leaving everything a string was the earlier
    /// choice, on the reasoning that the engine converts from the RDL field types anyway —
    /// which is true of arithmetic and false of formatting. A textbox Format of
    /// "MM/dd/yyyy" over a value that arrived as the string "2001-05-26" does nothing at
    /// all, so with string columns this suite could not measure any formatting work, and
    /// reported no change from a conversion fix that was in fact reaching the right cell.
    /// </summary>
    private static DataTable LoadCsvFixture(string path)
    {
        var lines = File.ReadAllLines(path);
        var header = SplitCsvLine(lines[0]);
        var rows = lines.Skip(1).Where(l => l.Length > 0).Select(SplitCsvLine).ToList();

        var table = new DataTable();
        for (int c = 0; c < header.Count; c++)
            table.Columns.Add(header[c], InferColumnType(rows, c));

        foreach (var values in rows)
        {
            var row = table.NewRow();
            for (int i = 0; i < table.Columns.Count && i < values.Count; i++)
            {
                if (values[i].Length == 0) { row[i] = DBNull.Value; continue; }
                row[i] = table.Columns[i].DataType == typeof(DateTime)
                    ? DateTime.ParseExact(values[i], FixtureDateFormat, CultureInfo.InvariantCulture)
                    : table.Columns[i].DataType == typeof(double)
                        ? double.Parse(values[i], CultureInfo.InvariantCulture)
                        : values[i];
            }
            table.Rows.Add(row);
        }
        return table;
    }

    // The fixture builder writes dates in one unambiguous shape, so this asks for that shape
    // exactly rather than letting TryParse guess — "2001" is a perfectly good date to
    // DateTime.TryParse, and a column of years would silently become a column of midnights.
    private const string FixtureDateFormat = "yyyy-MM-dd";

    private static Type InferColumnType(List<List<string>> rows, int column)
    {
        var values = rows.Where(r => column < r.Count).Select(r => r[column])
            .Where(v => v.Length > 0).ToList();
        if (values.Count == 0) return typeof(string);
        if (values.All(v => DateTime.TryParseExact(v, FixtureDateFormat,
                CultureInfo.InvariantCulture, DateTimeStyles.None, out _)))
            return typeof(DateTime);
        if (values.All(v => double.TryParse(v, NumberStyles.Float,
                CultureInfo.InvariantCulture, out _)))
            return typeof(double);
        return typeof(string);
    }

    private static List<string> SplitCsvLine(string line)
    {
        var fields = new List<string>();
        var field = new System.Text.StringBuilder();
        bool inQuotes = false;
        for (int i = 0; i < line.Length; i++)
        {
            char ch = line[i];
            if (inQuotes)
            {
                if (ch == '"' && i + 1 < line.Length && line[i + 1] == '"') { field.Append('"'); i++; }
                else if (ch == '"') inQuotes = false;
                else field.Append(ch);
            }
            else if (ch == '"') inQuotes = true;
            else if (ch == ',') { fields.Add(field.ToString()); field.Clear(); }
            else field.Append(ch);
        }
        fields.Add(field.ToString());
        return fields;
    }

    /// <summary>
    /// Agreement between the two renders' *ink* — the fraction of non-white pixels the two
    /// images share, over the union of their non-white pixels (Jaccard index), after
    /// aligning dimensions.
    ///
    /// This is the assertable metric, and <see cref="Compare"/>'s mean-pixel-difference is
    /// not, because these pages are 2-9% ink on white. Scoring a *pure white image* against
    /// these six references with that formula gives 93.9-98.5% — above any useful floor —
    /// so it passes a completely blank render and cannot distinguish "rendered correctly"
    /// from "rendered nothing". Ink agreement is 0 for a blank render by construction.
    ///
    /// Compared at a coarse grid rather than per pixel: the two engines place glyphs at
    /// slightly different subpixel offsets, so exact ink pixels rarely coincide even when
    /// the content is identical. A cell counts as inked if any pixel in it is inked, which
    /// tolerates that shift while still requiring content in the same places.
    /// </summary>
    private static double InkAgreementPercent(SKBitmap reference, SKBitmap ours, int cell = 8)
    {
        using SKBitmap oursResized = (reference.Width == ours.Width && reference.Height == ours.Height)
            ? ours.Copy()
            : ours.Resize(new SKImageInfo(reference.Width, reference.Height), new SKSamplingOptions(SKFilterMode.Linear));

        using SKBitmap a = reference.Copy(SKColorType.Bgra8888);
        using SKBitmap b = oursResized.Copy(SKColorType.Bgra8888);
        byte[] aBytes = a.Bytes;
        byte[] bBytes = b.Bytes;

        int cols = (a.Width + cell - 1) / cell;
        int rows = (a.Height + cell - 1) / cell;
        var aInk = new bool[cols * rows];
        var bInk = new bool[cols * rows];

        for (int y = 0; y < a.Height; y++)
        {
            for (int x = 0; x < a.Width; x++)
            {
                int o = (y * a.Width + x) * 4;
                int cellIndex = (y / cell) * cols + (x / cell);
                // "Ink" = visibly darker than the paper, summed across B/G/R.
                if (765 - (aBytes[o] + aBytes[o + 1] + aBytes[o + 2]) > 90) aInk[cellIndex] = true;
                if (765 - (bBytes[o] + bBytes[o + 1] + bBytes[o + 2]) > 90) bInk[cellIndex] = true;
            }
        }

        int intersection = 0, union = 0;
        for (int i = 0; i < aInk.Length; i++)
        {
            if (aInk[i] && bInk[i]) intersection++;
            if (aInk[i] || bInk[i]) union++;
        }
        return union == 0 ? 100.0 : 100.0 * intersection / union;
    }

    /// <summary>
    /// Aligns dimensions (resizing our render to the reference's size — real-Crystal PDFs
    /// and ours may come out at slightly different default page-to-pixel scaling), then
    /// computes a per-pixel RGB difference. Retained only for the red-heat diff image used
    /// in human triage: see <see cref="InkAgreementPercent"/> for why its score is not
    /// suitable as a pass criterion.
    /// </summary>
    private static (double SimilarityPercent, SKBitmap Diff) Compare(SKBitmap reference, SKBitmap ours)
    {
        using SKBitmap oursResized = (reference.Width == ours.Width && reference.Height == ours.Height)
            ? ours.Copy()
            : ours.Resize(new SKImageInfo(reference.Width, reference.Height), new SKSamplingOptions(SKFilterMode.Linear));

        SKBitmap a = reference.Copy(SKColorType.Bgra8888);
        SKBitmap b = oursResized.Copy(SKColorType.Bgra8888);
        var diff = new SKBitmap(new SKImageInfo(a.Width, a.Height, SKColorType.Bgra8888));

        byte[] aBytes = a.Bytes;
        byte[] bBytes = b.Bytes;
        byte[] diffBytes = new byte[aBytes.Length];

        long totalDiff = 0;
        int pixelCount = a.Width * a.Height;
        for (int i = 0; i < pixelCount; i++)
        {
            int o = i * 4; // B, G, R, A (Bgra8888)
            int db = Math.Abs(aBytes[o] - bBytes[o]);
            int dg = Math.Abs(aBytes[o + 1] - bBytes[o + 1]);
            int dr = Math.Abs(aBytes[o + 2] - bBytes[o + 2]);
            int d = db + dg + dr;
            totalDiff += d;

            byte intensity = (byte)Math.Min(255, d);
            diffBytes[o] = 0;              // B
            diffBytes[o + 1] = 0;          // G
            diffBytes[o + 2] = intensity;  // R — brighter red = more different
            diffBytes[o + 3] = 255;        // A
        }

        System.Runtime.InteropServices.Marshal.Copy(diffBytes, 0, diff.GetPixels(), diffBytes.Length);

        double maxPossibleDiff = (double)pixelCount * 255 * 3;
        double similarity = 100.0 * (1.0 - totalDiff / maxPossibleDiff);

        a.Dispose();
        b.Dispose();
        return (similarity, diff);
    }
}
